export const IDEAS_AGENT_BASE_PROMPT_NAME = 'IDEA_AGENT_BASE_SYSTEM_PROMPT';

export const SCRIPT_AGENT_BASE_SYSTEM_PROMPT =
  'SCRIPT_AGENT_BASE_SYSTEM_PROMPT';

export const SCREENPLAY_AGENT_BASE_SYSTEM_PROMPT =
  'SCREENPLAY_AGENT_BASE_SYSTEM_PROMPT';
